/**
 * Shared error codes used across all packages.
 */
export const ErrorCode = {
  // Authentication & Session
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_PAIRING_EXPIRED: 'AUTH_PAIRING_EXPIRED',
  AUTH_PAIRING_INVALID: 'AUTH_PAIRING_INVALID',

  // TRTC
  TRTC_ROOM_NOT_FOUND: 'TRTC_ROOM_NOT_FOUND',
  TRTC_JOIN_FAILED: 'TRTC_JOIN_FAILED',
  TRTC_SIG_EXPIRED: 'TRTC_SIG_EXPIRED',
  TRTC_SCREEN_CAPTURE_FAILED: 'TRTC_SCREEN_CAPTURE_FAILED',
  TRTC_CUSTOM_MESSAGE_TOO_LARGE: 'TRTC_CUSTOM_MESSAGE_TOO_LARGE',
  TRTC_BOT_CREATE_FAILED: 'TRTC_BOT_CREATE_FAILED',

  // Command Execution
  EXEC_COMMAND_BLOCKED: 'EXEC_COMMAND_BLOCKED',
  EXEC_COMMAND_TIMEOUT: 'EXEC_COMMAND_TIMEOUT',
  EXEC_COMMAND_FAILED: 'EXEC_COMMAND_FAILED',
  EXEC_CONFIRMATION_REQUIRED: 'EXEC_CONFIRMATION_REQUIRED',
  EXEC_CONFIRMATION_DENIED: 'EXEC_CONFIRMATION_DENIED',

  // Intent Classification
  INTENT_CLASSIFICATION_FAILED: 'INTENT_CLASSIFICATION_FAILED',
  INTENT_LOW_CONFIDENCE: 'INTENT_LOW_CONFIDENCE',

  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
